services:
  web:
    image: guzmanbenjamin/webmock:v1.0-alpha
    restart: on-failure
    ports:
      - "127.0.0.1:3000:3000" # change depending on your .env.prod
    volumes:
      - ".env.prod:/usr/src/.env"
    links:
      - "db:postgres"

  db:
    image: postgres
    volumes:
      - "./db/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh"
    environment:
      - "POSTGRES_PASSWORD=pass"
    restart: on-failure
