services:
  webmock:
    build: .
    ports:
      - "80:3000"
    restart: on-failure
    links:
      - "db:postgres"

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/home/guzman/projects/webmock/db/employees-init.sh:/docker-entrypoint-initdb.d/employees.init.sh"
      - "/home/guzman/projects/webmock/db/employees_data.sql:/employees.sql"
    environment:
      - "POSTGRES_PASSWORD=pass"
    restart: on-failure
